### PR TITLE
Don't use LFS

### LINKED ISSUE #1: max download bandwidth reached
copied from slack message by @charleygros 
~~~
git clone https://github.com/sct-data/exvivo-template.git
leads to:
Cloning into 'exvivo-template'...
remote: Enumerating objects: 61, done.
remote: Counting objects: 100% (61/61), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 61 (delta 19), reused 46 (delta 11), pack-reused 0
Unpacking objects: 100% (61/61), done.
Checking connectivity... done.
Downloading template/label_spinalsegments.nii.gz (2.2 MB)
Error downloading object: template/label_spinalsegments.nii.gz (f23c66e): Smudge error: Error downloading template/label_spinalsegments.nii.gz (f23c66e5bbc6c9417d34dea501e7b45c3de03902b5bd4f6cd9c275633cdd8908): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
Errors logged to /home/charley/Downloads/template_regi_test/exvivo-template/.git/lfs/logs/20210304T140208.350098739.log
Use `git lfs logs last` to view the log.
error: external filter git-lfs smudge -- %f failed 2
error: external filter git-lfs smudge -- %f failed
fatal: template/label_spinalsegments.nii.gz: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
~~~

This is indeed a known issue, see https://github.com/neuropoly/spinalcordtoolbox/issues/3214 where the issue is being discussed.

### PR DESCRIPTION
**Pull request by Drulex**
Closes #1 

What I did:

```
$  git-lfs untrack "*.nii.gz"                                                                                                                                                                                                        
Untracking "*.nii.gz"

$  git rm --cached "*.nii.gz"                                                                                                                                                                                                        
rm 'template/label_spinalsegments.nii.gz'                                                                                                                                                                                                                                                  
rm 'template/map_greymatter.nii.gz'
rm 'template/mask_spinalcord.nii.gz'
rm 'template/mask_spinalsegments.nii.gz'
rm 'template/template.nii.gz'

$   ghsplit split --extension=.nii.gz
```

Someone who would like to re-assemble the file:
```
$  ghsplit merge
```

Link to split/merge tool: https://github.com/Drulex/ghsplit

### CODE REVIEW

**Comment by Drulex** [comment]
Hmm I wonder why files show up as empty on GH interface:

image


They definitely have a size when I push..?

**Comment by Drulex** [comment]
> They definitely have a size when I push..?

Did a fresh clone and checked out my branch. Files look ok.

**Comment by jcohenadad** [comment]
> They definitely have a size when I push..?

yes, i've noticed this glitch on the GH website for binary files

**Review by jcohenadad — APPROVED** [review]
I could not test it (because of https://github.com/Drulex/ghsplit/issues/4), and it would be important to document how users can download the data https://github.com/sct-data/exvivo-template/issues/3

but this is an awesome first step, thank you so much!

**Comment by jcohenadad** [comment]
> I could not test it (because of Drulex/ghsplit#4)

issue fixed-- tested-- it works 🎉  (ie: i was able to reconstruct chunks of the dataset into the original 3D data)

**Pull request merged**
